### ISSUE TITLE
Is possible to cast a local file?

### ISSUE THREAD

**Issue by moiseslodeiro** [balloob/pychromecast#100]
I've trying to cast a local file using "file://...mp4" but seems that this not work. So, is possible to do that? thx

**Comment by rmkraus** [comment]
This is not possible. The chrome cast needs to have network access to the file in order to stream it and a web server is outside the scope of pychromecast. 

If you would like to do this in Python, consider spooling up a simple HTTP server. If you don't want to do this with code, you could always stand up an Apache server and host the file there.

**Comment by frakman1** [comment]
> If you would like to do this in Python, consider spooling up a simple HTTP server.

How would you do this in code? I know I can run `python3 -m http.server` to do this, but it would be cleaner if I could turn it on in code just before streaming and then turn it off immediately afterwards.
