### ISSUE TITLE
play_media is broken

### ISSUE THREAD

**Issue by theychx** [balloob/pychromecast#151]
@armills 
The following from the pychromecast README:
```
chromecasts = pychromecast.get_chromecasts()
cast = next(cc for cc in chromecasts if cc.device.friendly_name == "Living Room")
cast.wait()
mc = cast.media_controller
mc.play_media('http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', 'video/mp4')
```
does not work when run as a script, if the current app is not `Default Media Receiver`. Isn't `play_media` supposed to launch the `Default Media Receiver` and then play the media? Right now, it is only launching the app, but not playing anything. Interresting thing is, that if you run the script again after `Default Media Receiver` has been launched, it works as expected.

The problem is related to current `master`, and not `0.7.7`.

**Comment by armills** [comment]
Can you use `git bisect` to determine where the error was introduced? I suspect the problem was introduced here: https://github.com/balloob/pychromecast/commit/64472f2be3ebf33633f2f27643f2c72c7b1dca52

**Comment by theychx** [comment]
> I suspect the problem was introduced here: 64472f2

You were right. I don't have the time to look at the source code now, but I can take a look later.

**Comment by armills** [comment]
The biggest change is that `send_message` call is now being sent from a callback in the socket thread, instead of the calling thread.

In the readme, there is a time.sleep called later. If you aren't using that can you add a call to `mc.block_until_active()` at the end of your script? That might keep the script active until the play command is issued. If that works we should update the readme to include that after the `play_media` call, so the script doesn't continue until media is launched.

**Comment by theychx** [comment]
`block_until_active()` did the trick. Thanks!

I can do a PR for the readme later.
