### ISSUE TITLE
Volume is not updated in media_controller.status

### ISSUE THREAD

**Issue by theychx** [balloob/pychromecast#169]
```
In [3]: cast.status.volume_level
Out[3]: 0.800000011920929

In [4]: cast.media_controller.status.volume_level
Out[4]: 1

In [5]: cast.set_volume(0.5)
Out[5]: 0.5

In [6]: cast.status.volume_level
Out[6]: 0.5

In [7]: cast.media_controller.status.volume_level
Out[7]: 1
```
From a "Default Media Receiver" session. This behaviour seems to be consistent across apps, except for YouTube, where volume for some reason is updated as expected.

**Comment by noob-4-life** [comment]
Setting the 'Media' volume i.e. sending a volume request on the media namespace, is different from setting the 'Receiver' volume i.e. calling 'cast.set_volume'. [See here for reference](https://developers.google.com/cast/docs/reference/chrome/chrome.cast.media.VolumeRequest).

So calling 'cast.set_volume' will lead to a change in 'cast.status.volume_level'.
Calling 'cast.media_controller.set_volume' would lead to a change in 'cast.media_controller.status.volume_level'.  (Note: this method does not actually exist)

The MediaController class does not provide a method for setting the 'Media' volume. But, [judging from this stackoverflow post](https://stackoverflow.com/questions/39498516/remotemediaclient-setstreamvolume-doesnt-changing-cast-volume), it seems to serve no use anyway (other than to confuse people).

It may have been something implemented just for YouTube, and that's why it exists, but I don't really know.
