### ISSUE TITLE
Chromecasts on other mesh network nodes are hidden

### ISSUE THREAD

**Issue by stealthdave** [balloob/pychromecast#324]
I upgraded our home network to a Google Wifi home network, and now any Chromecasts, both audio and video, not on the same mesh node as the computer making the query are not seen.  Virtual "rooms" for Chromecast Audio _are_ seen, but physical devices on different nodes are not.

**Comment by HITChris** [comment]
I'm seeing what appears to be the same behavior - however I in my caae any devices connected via Ethernet to those other mesh nodes do show up. All devices connected to those nodes via WiFi though are not coming back.

**Comment by HITChris** [comment]
See [this post](https://www.reddit.com/r/GoogleWiFi/comments/dqbjqq/google_working_on_a_fix_for_the_update_that_broke/). Apparently a recent firmware update bricked the pucks' ability to forward the multicast DNS records of each cast device between each other. The workaround is to disable all but a single puck, so that all cast devices (and HA) are connected to the same router, but it sounds like a firmware fix is on the way.

**Comment by stealthdave** [comment]
It looks like this issue _has_ been fixed by Google; I'm now seeing all of my Chromecast Audio devices again.  Thanks to @HITChris for tracking this down!
