### ISSUE TITLE
module 'pychromecast' has no attribute 'get_chromecasts'

### ISSUE THREAD

**Issue by Thomas-Blondeau** [balloob/pychromecast#327]
Hello,

I just tried the very first example :
```
#!/usr/bin/env python3
import pychromecast
chromecasts = pychromecast.get_chromecasts()
[cc.device.friendly_name for cc in chromecasts]
```

I got the followinf error : 
```
Traceback (most recent call last):
  File "./testPychromecast.py", line 5, in <module>
    chromecasts = pychromecast.get_chromecasts()
AttributeError: module 'pychromecast' has no attribute 'get_chromecasts'
```

I installed Python 3.7 and I ran the following commands :

- python3 -m pip install -r requirements.txt
- python3 setup.py build
- python3 ./setup.py install

But nothing changed... Can somebody helps me please ? I'm in the python env since 1 month.

Thank you

**Comment by nefaspartim** [comment]
Hey, just a quick question. Are you running your script in the same directory where you checked out the pychromecast repo? If so, python will try to look in that directory instead of the module and complain. Rename the repo a la: mv pychromecast pychromecast.repo (or whatever) and then python3 yourscript.py
